# Generated by Django 4.2.7 on 2025-10-18 12:39

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, help_text="User's email address (used for login)", max_length=254, unique=True)),
                ('phone_number', models.CharField(db_index=True, help_text='Nigerian phone number for WhatsApp notifications', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in Nigerian format: +234XXXXXXXXXX or 0XXXXXXXXXX', regex='^(\\+234|0)[789][01]\\d{8}$')])),
                ('full_name', models.CharField(help_text="User's full name", max_length=255)),
                ('state', models.CharField(choices=[('abia', 'Abia'), ('adamawa', 'Adamawa'), ('akwa_ibom', 'Akwa Ibom'), ('anambra', 'Anambra'), ('bauchi', 'Bauchi'), ('bayelsa', 'Bayelsa'), ('benue', 'Benue'), ('borno', 'Borno'), ('cross_river', 'Cross River'), ('delta', 'Delta'), ('ebonyi', 'Ebonyi'), ('edo', 'Edo'), ('ekiti', 'Ekiti'), ('enugu', 'Enugu'), ('fct', 'Federal Capital Territory'), ('gombe', 'Gombe'), ('imo', 'Imo'), ('jigawa', 'Jigawa'), ('kaduna', 'Kaduna'), ('kano', 'Kano'), ('katsina', 'Katsina'), ('kebbi', 'Kebbi'), ('kogi', 'Kogi'), ('kwara', 'Kwara'), ('lagos', 'Lagos'), ('nasarawa', 'Nasarawa'), ('niger', 'Niger'), ('ogun', 'Ogun'), ('ondo', 'Ondo'), ('osun', 'Osun'), ('oyo', 'Oyo'), ('plateau', 'Plateau'), ('rivers', 'Rivers'), ('sokoto', 'Sokoto'), ('taraba', 'Taraba'), ('yobe', 'Yobe'), ('zamfara', 'Zamfara')], db_index=True, help_text='Nigerian state (used in 40% location-based algorithm)', max_length=50)),
                ('city', models.CharField(db_index=True, help_text='City/LGA (Local Government Area) - used in 40% location-based algorithm', max_length=100)),
                ('is_seller', models.BooleanField(default=False, help_text='True when user creates a store. Everyone is a buyer by default.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['email'], name='users_email_4b85f2_idx'), models.Index(fields=['phone_number'], name='users_phone_n_a3b1c5_idx'), models.Index(fields=['state'], name='users_state_bd654f_idx'), models.Index(fields=['city'], name='users_city_9c6023_idx'), models.Index(fields=['state', 'city'], name='users_state_99d491_idx'), models.Index(fields=['is_seller'], name='users_is_sell_85c761_idx')],
            },
        ),
    ]
