# Generated by Django 4.2.7 on 2025-11-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact_last_updated',
            field=models.DateTimeField(blank=True, help_text='Last time user updated phone_number (30-day limit to prevent abuse)', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location_last_updated',
            field=models.DateTimeField(blank=True, help_text='Last time user updated state/city (30-day limit to prevent abuse)', null=True),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['location_last_updated'], name='users_locatio_2b1283_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['contact_last_updated'], name='users_contact_027546_idx'),
        ),
    ]
