# Generated by Django 4.2.7 on 2025-10-18 15:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('stores', '0002_store_delivery_outside_lga_store_delivery_within_lga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Star rating from 1-5 (1=Poor, 5=Excellent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, help_text='Optional written review (max 1000 characters)', max_length=1000, null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin must approve before rating appears on store page')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the rating was approved by admin', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the rating was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time rating was updated')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved the rating', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings_approved', to=settings.AUTH_USER_MODEL)),
                ('buyer', models.ForeignKey(help_text='The buyer who left the rating', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(help_text='The order being rated (one rating per order)', on_delete=django.db.models.deletion.PROTECT, related_name='rating', to='orders.order')),
                ('store', models.ForeignKey(help_text='The store being rated', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='stores.store')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'db_table': 'ratings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', '-created_at'], name='ratings_store_i_b0e2cd_idx'), models.Index(fields=['is_approved'], name='ratings_is_appr_d6726c_idx'), models.Index(fields=['rating'], name='ratings_rating_105b29_idx')],
            },
        ),
    ]
