# Generated by Django for category choices
CATEGORIES = [
    ("mens_clothes", "Men Clothes"),
    ("ladies_clothes", "Ladies Clothes"),
    ("kids_clothes", "Kids Clothes"),
    ("beauty", "Beauty"),
    ("body_accessories", "Body Accessories"),
    ("clothing_extras", "Clothing Extras"),
    ("bags", "Bags"),
    ("wigs", "Wigs"),
    ("body_scents", "Body Scents"),
]
STORE_CATEGORIES = CATEGORIES
