# Generated by Django 4.2.7 on 2025-10-18 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='NGN', editable=False, max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Can be frozen if suspicious activity detected')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='One wallet per user', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'db_table': 'wallets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('ESCROW_HOLD', 'Escrow Hold'), ('ESCROW_RELEASE', 'Escrow Release'), ('REFUND', 'Refund'), ('WITHDRAWAL', 'Withdrawal')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in Naira', max_digits=12)),
                ('reference', models.CharField(db_index=True, help_text='Unique reference for idempotency (prevents duplicate transactions)', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Transaction description')),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='Wallet balance before transaction', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Wallet balance after transaction', max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional transaction data (order_id, paystack_ref, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'db_table': 'wallet_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='wallet_tran_wallet__3d47ad_idx'), models.Index(fields=['transaction_type'], name='wallet_tran_transac_377ecc_idx'), models.Index(fields=['reference'], name='wallet_tran_referen_531c6d_idx'), models.Index(fields=['created_at'], name='wallet_tran_created_33245a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user'], name='wallets_user_id_9fb6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['is_active'], name='wallets_is_acti_3744ed_idx'),
        ),
    ]
