# Generated by Django 4.2.7 on 2025-10-20 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(help_text='Name of the bank', max_length=100)),
                ('bank_code', models.CharField(help_text='Paystack bank code (e.g., 058 for GTBank)', max_length=10)),
                ('account_number', models.CharField(help_text='10-digit account number', max_length=10)),
                ('account_name', models.CharField(help_text='Account holder name (from bank verification)', max_length=200)),
                ('paystack_recipient_code', models.CharField(blank=True, help_text='Paystack transfer recipient code', max_length=100)),
                ('is_verified', models.BooleanField(default=False, help_text='Bank account verified with Paystack')),
                ('is_default', models.BooleanField(default=False, help_text='Default withdrawal account')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'db_table': 'bank_accounts',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Withdrawal amount (before fees)', max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=0, help_text='Paystack transfer fee', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Amount after fees (credited to bank)', max_digits=12)),
                ('reference', models.CharField(db_index=True, help_text='Unique withdrawal reference', max_length=100, unique=True)),
                ('paystack_transfer_code', models.CharField(blank=True, help_text='Paystack transfer code', max_length=100)),
                ('paystack_transfer_id', models.BigIntegerField(blank=True, help_text='Paystack transfer ID', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for failure (if failed)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='wallets.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='wallets.wallet')),
                ('wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal', to='wallets.wallettransaction')),
            ],
            options={
                'verbose_name': 'Withdrawal',
                'verbose_name_plural': 'Withdrawals',
                'db_table': 'withdrawals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='withdrawals_user_id_df8772_idx'), models.Index(fields=['status'], name='withdrawals_status_ddef8f_idx'), models.Index(fields=['reference'], name='withdrawals_referen_0dd80e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['user'], name='bank_accoun_user_id_ac4793_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['is_default'], name='bank_accoun_is_defa_cf6505_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('user', 'account_number')},
        ),
    ]
