# Generated by Django 4.2.7 on 2025-11-09 17:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0002_bankaccount_withdrawal_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('user', 'account_number', 'bank_code')},
        ),
    ]
