# Generated by Django 4.2.7 on 2025-11-06 03:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('complaint_type', models.CharField(choices=[('SELLER', 'Report Seller'), ('BUYER', 'Report Buyer'), ('ORDER', 'Report Order'), ('TRANSACTION', 'Report Transaction')], help_text='Type of complaint', max_length=20)),
                ('category', models.CharField(choices=[('FRAUD', 'Fraudulent Activity'), ('HARASSMENT', 'Harassment or Abuse'), ('FAKE_PRODUCT', 'Fake/Counterfeit Product'), ('POOR_SERVICE', 'Poor Customer Service'), ('SCAM', 'Scam/Deception'), ('SPAM', 'Spam or Unwanted Messages'), ('NOT_RECEIVED', 'Product Not Received'), ('WRONG_ITEM', 'Wrong Item Delivered'), ('DAMAGED', 'Damaged Product'), ('NOT_AS_DESCRIBED', 'Not As Described'), ('LATE_DELIVERY', 'Late Delivery'), ('QUALITY_ISSUE', 'Quality Issue'), ('PAYMENT_FAILED', 'Payment Failed'), ('DOUBLE_CHARGE', 'Double Charged'), ('REFUND_ISSUE', 'Refund Not Received'), ('WALLET_ISSUE', 'Wallet Issue'), ('UNAUTHORIZED', 'Unauthorized Transaction'), ('OTHER', 'Other Issue')], help_text='Specific category of the complaint', max_length=30)),
                ('urgency', models.CharField(choices=[('LOW', 'Low - Not urgent'), ('MEDIUM', 'Medium - Needs attention'), ('HIGH', 'High - Important'), ('URGENT', 'Urgent - Immediate action required')], default='MEDIUM', help_text='Urgency level of the complaint', max_length=10)),
                ('reporter_email', models.EmailField(help_text="Reporter's email for follow-up", max_length=254)),
                ('reporter_phone', models.CharField(blank=True, help_text="Reporter's phone (optional)", max_length=20)),
                ('subject', models.CharField(help_text='Brief complaint subject', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('reported_user_name', models.CharField(blank=True, help_text='Name of reported user/store (if user is deleted)', max_length=200)),
                ('order_id', models.CharField(blank=True, help_text='Order number (for order complaints)', max_length=100)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID (for transaction complaints)', max_length=100)),
                ('transaction_type', models.CharField(blank=True, help_text='Type of transaction (deposit/withdrawal)', max_length=50)),
                ('attachment', models.FileField(blank=True, help_text='Screenshot or evidence (optional)', null=True, upload_to='complaints/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current status of the complaint', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin/support team')),
                ('admin_response', models.TextField(blank=True, help_text='Response sent to the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_user', models.ForeignKey(blank=True, help_text='User being reported (for seller/buyer reports)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(help_text='User who filed the complaint', on_delete=django.db.models.deletion.CASCADE, related_name='complaints_filed', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Admin who resolved the complaint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'db_table': 'complaints',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['complaint_type', 'status'], name='complaints_complai_951436_idx'), models.Index(fields=['reporter', '-created_at'], name='complaints_reporte_761915_idx'), models.Index(fields=['status', '-created_at'], name='complaints_status_dbbea4_idx'), models.Index(fields=['urgency', '-created_at'], name='complaints_urgency_1f44b9_idx')],
            },
        ),
    ]
