# Generated by Django 4.2.7 on 2025-10-18 14:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount held in escrow (product + delivery)', max_digits=12)),
                ('status', models.CharField(choices=[('HELD', 'Funds Held in Escrow'), ('RELEASED', 'Funds Released to Seller'), ('REFUNDED', 'Funds Refunded to Buyer')], db_index=True, default='HELD', help_text='Current escrow status', max_length=20)),
                ('debit_reference', models.CharField(help_text="Reference for buyer's wallet debit transaction", max_length=100, unique=True)),
                ('credit_reference', models.CharField(blank=True, help_text="Reference for seller's wallet credit transaction (when released)", max_length=100, null=True, unique=True)),
                ('refund_reference', models.CharField(blank=True, help_text="Reference for buyer's wallet refund transaction (when refunded)", max_length=100, null=True, unique=True)),
                ('held_at', models.DateTimeField(auto_now_add=True, help_text='When funds were held in escrow')),
                ('released_at', models.DateTimeField(blank=True, help_text='When funds were released to seller', null=True)),
                ('refunded_at', models.DateTimeField(blank=True, help_text='When funds were refunded to buyer', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this escrow transaction')),
                ('buyer_wallet', models.ForeignKey(help_text="Buyer's wallet (money came from here)", on_delete=django.db.models.deletion.PROTECT, related_name='escrow_debits', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'Escrow Transaction',
                'verbose_name_plural': 'Escrow Transactions',
                'db_table': 'escrow_transactions',
                'ordering': ['-held_at'],
            },
        ),
    ]
