# Generated by Django 4.2.7 on 2025-10-18 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escrow', '0001_initial'),
        ('wallets', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowtransaction',
            name='order',
            field=models.OneToOneField(help_text='Order this escrow is for', on_delete=django.db.models.deletion.PROTECT, related_name='escrow', to='orders.order'),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='seller_wallet',
            field=models.ForeignKey(help_text="Seller's wallet (money will go here)", on_delete=django.db.models.deletion.PROTECT, related_name='escrow_credits', to='wallets.wallet'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['status'], name='escrow_tran_status_e7bf77_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['held_at'], name='escrow_tran_held_at_250a39_idx'),
        ),
    ]
