# Generated by Django 4.2.7 on 2025-10-18 13:37

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Auto-generated: COVU + user unique ID (editable later)', max_length=255, unique=True)),
                ('description', models.TextField(default='This will be a very great store.', help_text='Default description (editable later)')),
                ('logo', cloudinary.models.CloudinaryField(blank=True, help_text='Default logo from Cloudinary (editable later)', max_length=255, null=True, verbose_name='store_logos')),
                ('state', models.CharField(choices=[('abia', 'Abia'), ('adamawa', 'Adamawa'), ('akwa_ibom', 'Akwa Ibom'), ('anambra', 'Anambra'), ('bauchi', 'Bauchi'), ('bayelsa', 'Bayelsa'), ('benue', 'Benue'), ('borno', 'Borno'), ('cross_river', 'Cross River'), ('delta', 'Delta'), ('ebonyi', 'Ebonyi'), ('edo', 'Edo'), ('ekiti', 'Ekiti'), ('enugu', 'Enugu'), ('fct', 'Federal Capital Territory'), ('gombe', 'Gombe'), ('imo', 'Imo'), ('jigawa', 'Jigawa'), ('kaduna', 'Kaduna'), ('kano', 'Kano'), ('katsina', 'Katsina'), ('kebbi', 'Kebbi'), ('kogi', 'Kogi'), ('kwara', 'Kwara'), ('lagos', 'Lagos'), ('nasarawa', 'Nasarawa'), ('niger', 'Niger'), ('ogun', 'Ogun'), ('ondo', 'Ondo'), ('osun', 'Osun'), ('oyo', 'Oyo'), ('plateau', 'Plateau'), ('rivers', 'Rivers'), ('sokoto', 'Sokoto'), ('taraba', 'Taraba'), ('yobe', 'Yobe'), ('zamfara', 'Zamfara')], db_index=True, help_text="Copied from user's state", max_length=50)),
                ('city', models.CharField(db_index=True, help_text="Copied from user's city", max_length=100)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Updated when ratings are added', max_digits=3)),
                ('product_count', models.IntegerField(default=0, help_text='Auto-updated when products are added/removed')),
                ('is_active', models.BooleanField(default=True, help_text='Store can be deactivated by admin or seller')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(help_text='One store per seller (for MVP)', on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'db_table': 'stores',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state', 'city'], name='stores_state_57786d_idx'), models.Index(fields=['is_active'], name='stores_is_acti_89b637_idx'), models.Index(fields=['created_at'], name='stores_created_4eedc7_idx'), models.Index(fields=['average_rating'], name='stores_average_9c1ffb_idx')],
            },
        ),
    ]
