# Generated by Django 4.2.7 on 2025-10-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='delivery_outside_lga',
            field=models.DecimalField(decimal_places=2, default=2500.0, help_text="Delivery fee for buyers outside seller's city/LGA (₦)", max_digits=10),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_within_lga',
            field=models.DecimalField(decimal_places=2, default=1000.0, help_text='Delivery fee for buyers in same city/LGA (₦)', max_digits=10),
        ),
    ]
