# Generated by Django 4.2.7 on 2025-10-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_delivery_outside_lga_store_delivery_within_lga'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.CharField(choices=[('mens_clothes', 'Men Clothes'), ('ladies_clothes', 'Ladies Clothes'), ('kids_clothes', 'Kids Clothes'), ('beauty', 'Beauty'), ('body_accessories', 'Body Accessories'), ('clothing_extras', 'Clothing Extras'), ('bags', 'Bags'), ('wigs', 'Wigs'), ('body_scents', 'Body Scents')], db_index=True, default='other', help_text='Store category for filtering (editable)', max_length=50),
        ),
    ]
