# Generated by Django 4.2.7 on 2025-10-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='delivery_outside_state',
            field=models.DecimalField(decimal_places=2, default=4000.0, help_text="Delivery fee for buyers outside seller's state (₦)", max_digits=10),
        ),
    ]
