# Generated by Django 4.2.7 on 2025-11-02 17:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_delivery_outside_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='seller_photo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="Seller's profile photo for transparency (editable later)", max_length=255, null=True, verbose_name='seller_photos'),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Store logo/brand image (editable later)', max_length=255, null=True, verbose_name='store_logos'),
        ),
    ]
