# Generated by Django 4.2.7 on 2025-11-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_store_seller_photo_alter_store_logo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['name'], name='stores_name_b54c6a_idx'),
        ),
    ]
