# Generated by Django 4.2.7 on 2025-10-18 14:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, help_text='Quantity ordered (always 1 for MVP)', validators=[django.core.validators.MinValueValidator(1)])),
                ('product_price', models.DecimalField(decimal_places=2, help_text='Product price at time of order (snapshot)', max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, help_text='Delivery fee based on buyer location', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='product_price + delivery_fee', max_digits=12)),
                ('delivery_address', models.TextField(help_text='Full delivery address provided by buyer')),
                ('status', models.CharField(choices=[('PENDING', 'Pending - Waiting Seller Acceptance'), ('ACCEPTED', 'Accepted - Seller Preparing Order'), ('DELIVERED', 'Delivered - Waiting Buyer Confirmation'), ('CONFIRMED', 'Confirmed - Transaction Complete'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', help_text='Current order status', max_length=20)),
                ('cancelled_by', models.CharField(blank=True, choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller')], help_text='Who cancelled the order (buyer or seller)', max_length=10, null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Optional reason for cancellation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When order was placed')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When seller accepted the order', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When seller marked as delivered', null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When buyer confirmed receipt', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When order was cancelled', null=True)),
                ('buyer', models.ForeignKey(help_text='User who placed the order', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Product being ordered', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.product')),
                ('seller', models.ForeignKey(help_text='Store owner who will fulfill the order', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='orders_status_762191_idx'), models.Index(fields=['buyer', 'status'], name='orders_buyer_i_de73e4_idx'), models.Index(fields=['seller', 'status'], name='orders_seller__0c477d_idx'), models.Index(fields=['created_at'], name='orders_created_77e2b9_idx')],
            },
        ),
    ]
