# Generated by Django 4.2.7 on 2025-11-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_category_snapshot',
            field=models.CharField(blank=True, default='', help_text='Product category at time of order (snapshot)', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='product_image_snapshot',
            field=models.URLField(blank=True, default='', help_text='Product image URL at time of order (snapshot)', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='product_name_snapshot',
            field=models.CharField(blank=True, default='', help_text='Product name at time of order (snapshot)', max_length=200),
        ),
    ]
