# Generated by Django 4.2.7 on 2025-10-19 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ORDER_CREATED', 'New Order Created'), ('ORDER_ACCEPTED', 'Order Accepted by Seller'), ('ORDER_DELIVERED', 'Order Delivered'), ('ORDER_CONFIRMED', 'Order Confirmed by Buyer'), ('ORDER_CANCELLED', 'Order Cancelled'), ('PAYMENT_RECEIVED', 'Payment Received'), ('REFUND_ISSUED', 'Refund Issued')], help_text='Type of notification', max_length=50)),
                ('title', models.CharField(help_text='Notification title/subject', max_length=200)),
                ('message', models.TextField(help_text='Full notification message content')),
                ('is_sent', models.BooleanField(default=False, help_text='Whether notification was successfully sent')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When notification was sent', null=True)),
                ('delivery_method', models.CharField(default='CONSOLE', help_text='How notification was delivered (CONSOLE, WHATSAPP, EMAIL, SMS)', max_length=50)),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When notification was created')),
                ('order', models.ForeignKey(blank=True, help_text='Related order (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='orders.order')),
                ('user', models.ForeignKey(help_text='User who should receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'), models.Index(fields=['is_sent'], name='notificatio_is_sent_7b3d0f_idx')],
            },
        ),
    ]
