# Generated by Django 4.2.7 on 2025-10-18 14:12

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in Nigerian Naira (NGN)', max_digits=12)),
                ('category', models.CharField(choices=[('mens_clothes', 'Men Clothes'), ('ladies_clothes', 'Ladies Clothes'), ('kids_clothes', 'Kids Clothes'), ('beauty', 'Beauty'), ('body_accessories', 'Body Accessories'), ('clothing_extras', 'Clothing Extras'), ('bags', 'Bags'), ('wigs', 'Wigs'), ('body_scents', 'Body Scents')], db_index=True, help_text='Product category', max_length=50)),
                ('images', cloudinary.models.CloudinaryField(help_text='Primary product image', max_length=255, verbose_name='product_images')),
                ('premium_quality', models.BooleanField(default=False, help_text='Premium quality materials')),
                ('durable', models.BooleanField(default=False, help_text='Durable and long-lasting')),
                ('modern_design', models.BooleanField(default=False, help_text='Modern and stylish design')),
                ('easy_maintain', models.BooleanField(default=False, help_text='Easy to maintain and clean')),
                ('is_active', models.BooleanField(default=True, help_text='Product is visible and available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(help_text='Store that owns this product', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='products_categor_fce6e6_idx'), models.Index(fields=['is_active'], name='products_is_acti_cb485f_idx'), models.Index(fields=['created_at'], name='products_created_e1ba5f_idx'), models.Index(fields=['store', 'is_active'], name='products_store_i_7e53ff_idx')],
            },
        ),
    ]
